org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.19.2
minecraft_version_range=[1.19.2,1.20)
forge_version=43.4.0
forge_version_range=[43,)
loader_version_range=[43,)
mapping_channel=official
mapping_version=1.19.2

mod_id=goety_spillage
mod_name=Goety and Spillage
mod_license=MIT License
mod_version=1.19-1.0.0
mod_group_id=com.Polarice3.goety_spillage
mod_authors=Polarice3, YellowbrossProduction
mod_description=Compat mod between Goety and Illage & Spillage.

jei_version=11.5.2.1007
curio_version=5.1.1.0
patchouli_version=77
