modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="goety_spillage"
version="${mod_version}"
displayName="${mod_name}"
logoFile="logo.png"
credits="YellowbrossProduction for making Illage and Spillage, and TheDarkPeasant for the 1.20 port/continuation."
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.goety_spillage]]
modId="forge"
mandatory=true
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.goety_spillage]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.goety_spillage]]
modId="goety"
mandatory=true
versionRange="[2.5.21.2,)"
ordering="NONE"
side="BOTH"
[[dependencies.goety_spillage]]
modId="illageandspillage"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"
